SET NAMES utf8;

CREATE DATABASE IF NOT EXISTS dmshop CHARSET=utf8;

USE dmshop;

CREATE TABLE IF NOT EXISTS users(
    uid INT AUTO_INCREMENT PRIMARY KEY,
    uname VARCHAR(50) NOT NULL,
    upwd VARCHAR(50) NOT NULL
); 

INSERT INTO users VALUES(1, 'wxamlzm', '12345678');
